// <auto-generated />
namespace UniversumOOP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Address_phoneNo_cols : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_phoneNo_cols));
        
        string IMigrationMetadata.Id
        {
            get { return "202112231047052_Address_phoneNo_cols"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
